# Generated by Django 3.1.4 on 2021-01-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='stock',
            name='location',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='stock',
            name='size',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
