# Generated by Django 3.1.4 on 2021-01-04 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210104_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='description',
        ),
    ]
