# Generated by Django 3.1.4 on 2021-01-08 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_stock_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='threshold',
            field=models.IntegerField(default=1),
        ),
    ]
