# Generated by Django 3.1.4 on 2021-01-13 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20210109_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinCard',
            fields=[
                ('billno', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=254)),
                ('gstin', models.CharField(max_length=15)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binsupplier', to='transactions.supplier')),
            ],
        ),
    ]
