# Generated by Django 3.1.4 on 2021-01-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_bincard'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
