# Generated by Django 3.1.4 on 2021-01-14 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_saleitem_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='phone',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
